sudo: required
language: java
jdk:
  - openjdk10
before_install:
  - chmod +x gradlew
services:
  - docker
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - docker
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bren@juanantonio.info
script:
  - ./gradlew dockerTest
after_success:
  - bash <(curl -s https://codecov.io/bash)
