sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - docker
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - docker
script: ./gradlew dockerTest